name: sync to cloudflare r2

on:
  push:
    branches:
      - main
      # runs the workflow on push to the main branch
    paths-ignore:
      - '**/README.md'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        # checks out the repository

      - name: rclone setup
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          echo ${{ secrets.RCLONE_CONFIG }} | base64 -d > ~/.config/rclone/rclone.conf
        # installs rclone, sets up the rclone config file with the contents of the RCLONE_CONFIG secret encoded in base64

      - name: sync
        run: |
          rclone --multi-thread-streams 4 sync ./cdn/ r2:wuthering-waves-cdn --config ~/.config/rclone/rclone.conf --exclude "*.ini" --progress --update --no-update-modtime
        # syncs the contents of the ./r2/ directory to the wuthering-waves-cdn r2 bucket, with the --update flag to only upload new files and skip existing ones
